services:
    pgweb:
        container_name: ddev-${DDEV_SITENAME}-pgweb
        image: sosedoff/pgweb:latest
        restart: no
        environment:
            - VIRTUAL_HOST=pgweb.$DDEV_HOSTNAME
            - HTTPS_EXPOSE=443:8081
            - PGWEB_DATABASE_URL=postgres://db:db@db:5432/db?sslmode=disable
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: ${DDEV_APPROOT}
        ports:
            - "8081"
        depends_on:
            - db
        volumes:
            - ".:/mnt/ddev_config"
            - "ddev-global-cache:/mnt/ddev-global-cache"
